name: Ruby 2.5
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - '*'
jobs:
  tests:
    env:
      TEST_ES_SERVER: http://localhost:9200
      RAILS_VERSIONS: '5.0,6.0'
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Increase system limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: opensearch-project/opensearch-ruby/.github/actions/opensearch@1.x
      with:
        cluster-version: 1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Bundle
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install
        bundle exec rake bundle:clean
        bundle exec rake bundle:install
    - name: Test opensearch-rails
      run: cd opensearch-rails && bundle exec rake test:all
    - name: Test opensearch-persistence
      run: cd opensearch-persistence && bundle exec rake test:all
    - name: Test opensearch-model
      run: cd opensearch-model && bundle exec rake test:all

